new-session -d -s comms
new-session -d -s servers
new-session -s main
new-window -d -S -t comms: -n mail-bmcginty.us mutt -F ~/.mutt/bmmcginty@bmcginty.us.muttrc
new-window -d -S -t comms: -n mail-bmmcginty mutt -f /var/mail/bmmcginty
new-window -d -S -t comms: -n mail-gmail mutt -F ~/.mutt/brandon.mcginty@gmail.com.muttrc
new-window -d -S -t comms: -n tiny tiny
#new-window -d -S -t comms: -n jabber profannity
if-shell 'tmux source-file ~/.tmux.private.conf' ''
#new-window -t servers: -n tib xorg-0 ~/cr/tib dummy-1920x1080.conf
#new-window -t servers: -n firefox ~/bin/firefox
# if sharing ssh is desired
#/home/bmmcginty/bin/ngrok tcp 22
